# Generated by Django 5.0.7 on 2024-08-07 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Blog',
        ),
    ]
